### ISSUE TITLE
ppxlib

### ISSUE THREAD

**Issue by idkjs** [etanol/bs-async#1]
Any plans on updating to ppxlib?

**Comment by etanol** [comment]
Not really, the reasons are explained [in this comment][c].

But given the focus shift towards [Rescript][r] and the uncertainty of the BuckleScript forks, this package can be considered a finished learning experiment.

I don't think it's going to be useful to anyone at this point.

[c]: /etanol/bs-async/blob/master/native/bs_async.ml#L1-L13
[r]: https://rescript-lang.org/
